ALTER TABLE user_settings
  ADD COLUMN IF NOT EXISTS nudges_enabled INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS nudges_morning_on INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS nudges_morning_time TEXT NOT NULL DEFAULT '07:00',
  ADD COLUMN IF NOT EXISTS nudges_morning_days TEXT NOT NULL DEFAULT 'mon,tue,wed,thu,fri',
  ADD COLUMN IF NOT EXISTS nudges_evening_on INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS nudges_evening_time TEXT NOT NULL DEFAULT '21:00',
  ADD COLUMN IF NOT EXISTS nudges_evening_days TEXT NOT NULL DEFAULT 'mon,tue,wed,thu,fri,sat,sun',
  ADD COLUMN IF NOT EXISTS nudges_tone TEXT NOT NULL DEFAULT 'soft',
  ADD COLUMN IF NOT EXISTS nudges_quiet_mode INTEGER NOT NULL DEFAULT 0;
